name: hntd
description: Hana bible project.

publish_to: "none"
version: 2.0.8

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    cloud_firestore: ^4.7.1
    cupertino_icons: ^1.0.5
    equatable: ^2.0.5
    firebase_auth: ^4.6.1
    firebase_core: ^2.16.0
    firebase_ui_auth: ^1.10.0
    firebase_ui_firestore: ^1.5.1
    flutter:
        sdk: flutter
    flutter_riverpod: ^2.3.6
    flutter_svg: ^2.0.9
    go_router: 7.1.1
    intl: ^0.18.0
    rxdart: ^0.27.7
    shared_preferences: ^2.1.1
    # the annotation package containing @riverpod
    riverpod_annotation: 2.1.1
    # calendar
    flutter_calendar_carousel: ^2.4.2
    provider: ^6.0.5
    cached_network_image: ^3.2.3
    firebase_database: ^10.2.6
    calendar_date_picker2: ^0.5.3
    fluttertoast: ^8.0.8
    flutter_cache_manager: ^3.3.1
    flutter_local_notifications: ^9.3.2
    permission_handler: ^10.0.0
    timezone: ^0.8.0
    # url_launcher: ^6.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    mocktail: ^0.3.0
    random_string: ^2.3.1
    flutter_lints: ^2.0.1
    # a tool for running code generators
    build_runner: 2.4.4
    # the code generator
    riverpod_generator: 2.2.3
    # riverpod_lint makes it easier to work with Riverpod
    riverpod_lint: 1.3.2
    # import custom_lint too as riverpod_lint depends on it
    custom_lint: 0.4.0
    flutter_launcher_icons: "^0.13.1"

flutter:
    uses-material-design: true
    assets:
        - assets/Open-Bible.svg
        - assets/json/
        - assets/images/
    fonts:
        - family: NotoSerifKR
          fonts:
              - asset: fonts/NotoSerifKR-Regular.otf
              - asset: fonts/NotoSerifKR-Bold.otf
                weight: 700

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"
    web:
        generate: true
    windows:
    macos:
        generate: true
