// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAbSbwQsa8uWMwWfXu_p_0HNMwuotSnrY',
    appId: '1:30352074708:web:891c390a0ba97c506c1841',
    messagingSenderId: '30352074708',
    projectId: 'hana-tongdok-4887a',
    authDomain: 'hana-tongdok-4887a.firebaseapp.com',
    storageBucket: 'hana-tongdok-4887a.appspot.com',
    measurementId: 'G-PRK1TBGKD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATxr_GCVVmeQE_tJxnlTkOZgOiGZ1Cz2g',
    appId: '1:30352074708:android:89128b64a510ffed6c1841',
    messagingSenderId: '30352074708',
    projectId: 'hana-tongdok-4887a',
    storageBucket: 'hana-tongdok-4887a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpepg0a_sVq81xDggtFOCpska3Z1Ef1cE',
    appId: '1:30352074708:ios:440cb5a7b19016336c1841',
    messagingSenderId: '30352074708',
    projectId: 'hana-tongdok-4887a',
    storageBucket: 'hana-tongdok-4887a.appspot.com',
    iosClientId: '30352074708-spndhlsmttk3p5ktq8fhvmffie7lu6h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase',
  );
}
