// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_5jTN6J3WFY5G1NwGpZSTQr8GscfEs4',
    appId: '1:192180947367:web:566bb251efd98211a1ce82',
    messagingSenderId: '192180947367',
    projectId: 'hana-tongdok2',
    authDomain: 'hana-tongdok2.firebaseapp.com',
    storageBucket: 'hana-tongdok2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6t_IkRSln5QkQvltsovHzW6oDMHI7Dk',
    appId: '1:192180947367:android:65ab5b2548a783fda1ce82',
    messagingSenderId: '192180947367',
    projectId: 'hana-tongdok2',
    storageBucket: 'hana-tongdok2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSWqq6wSvHCUDd0dfmp7s8cO6BTCR1KFM',
    appId: '1:192180947367:ios:b4e5936a5810f41ea1ce82',
    messagingSenderId: '192180947367',
    projectId: 'hana-tongdok2',
    storageBucket: 'hana-tongdok2.appspot.com',
    iosClientId: '192180947367-rokkoju8pf9ukngn69do4t9rpsjcjlmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSWqq6wSvHCUDd0dfmp7s8cO6BTCR1KFM',
    appId: '1:192180947367:ios:8d53a7406f361f8ca1ce82',
    messagingSenderId: '192180947367',
    projectId: 'hana-tongdok2',
    storageBucket: 'hana-tongdok2.appspot.com',
    iosClientId: '192180947367-4eqgs13jbalm38na23idso7ld9ppe1tb.apps.googleusercontent.com',
    iosBundleId: 'com.example.starterArchitectureFlutterFirebase.RunnerTests',
  );
}
